name: Workflow That Won't Be Triggered
on:
  push:
    branches: 
      - main
  workflow_dispatch:


jobs:
  create-prerequired:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display Secret
        run: echo ${{ secrets.MY_SECRET }}
